### ISSUE TITLE
Get database dump from legacy application

### ISSUE THREAD

**Issue by bess** [pulibrary/oawaiver#2]

**Comment by jrgriffiniii** [comment]
As of 09:24, members of OIT have assisted me with resetting the RSA soft token needed to access the server with the legacy application:

```bash
❯ ssh libvijrg@epoxy.princeton.edu
[...]
Enter PASSCODE:
[...]

IMPORTANT EMAIL ADDRESS

        All Questions     helpdesk@Princeton.EDU

libvijrg@eisess204l:~ $
```

**Comment by jrgriffiniii** [comment]
I have attempted to ensure that I *am* using the correct legacy credentials for the system user `oar`, however, it now seems to be the case that either these credentials have been updated or, more likely, that password-only authentication over the SSH has been disabled. I have submitted a support request to OIT in order to advance this:

https://princeton.service-now.com/service?id=ticket&table=incident&sys_id=36ed1ea01b6934507ceedca1b24bcb89&view=sp

**Comment by jrgriffiniii** [comment]
This has been exported successfully, and uploaded to https://drive.google.com/file/d/18HIczcqIgQ7ZPZWwLYWb3N0Ni68NMJ0S/view
